- metadata.tex
* Added shadow to list dots and header elements
* Adjusted left, right, and top margins of document
> General formatting / template changes

- coops/sentinels.tex
- templates/cooperative.tex
> Make scenario and template 2-columnar

- sections/credits.tex
> Credits - text corrections

- clash/bloody_grail.tex
> Bloody Grail - text corrections

- coops/titans_stronghold.tex
- templates/campaign.tex
- templates/cooperative.tex
> Titans' Stronghold - text corrections

- metadata.tex
> Fix header space

- .github/workflows/check-po4a-entries.yaml
- po4a.cfg
- translations/back_cover.tex/back_cover.tex.pot
- translations/back_cover.tex/cs.po
- translations/back_cover.tex/fr.po
- translations/back_cover.tex/pl.po
- translations/inferno_devilish_plan.tex/cs.po
- translations/inferno_devilish_plan.tex/fr.po
- translations/inferno_devilish_plan.tex/inferno_devilish_plan.tex.pot
- translations/inferno_devilish_plan.tex/pl.po
- translations/sentinels.tex/cs.po
- translations/sentinels.tex/fr.po
- translations/sentinels.tex/pl.po
- translations/sentinels.tex/sentinels.tex.pot
Here's an example of a failing workflow: https://github.com/qwrtln/Homm3BG-mission-book/actions/runs/9746221629/job/26896004180
Marking this check as mandatory to maintain order.
> Add po4a.cfg entries check

- coops/sentinels.tex
- metadata.tex
- translations/sentinels.tex/cs.po
- translations/sentinels.tex/fr.po
- translations/sentinels.tex/pl.po
- translations/sentinels.tex/sentinels.tex.pot
> typesetting fixes for Sentinel

- coops/emerald_island.tex
- coops/titans_stronghold.tex
- translations/emerald_island.tex/cs.po
- translations/emerald_island.tex/emerald_island.tex.pot
- translations/emerald_island.tex/fr.po
- translations/emerald_island.tex/pl.po
- translations/titans_stronghold.tex/cs.po
- translations/titans_stronghold.tex/fr.po
- translations/titans_stronghold.tex/pl.po
- translations/titans_stronghold.tex/titans_stronghold.tex.pot
> Fix formulas in titan and emerald

- clash/bloody_grail.tex
- translations/bloody_grail.tex/bloody_grail.tex.pot
- translations/bloody_grail.tex/cs.po
- translations/bloody_grail.tex/fr.po
- translations/bloody_grail.tex/pl.po
> fix typesetting in bloody grail

- campaigns/inferno_deal_with_the_devil.tex
- campaigns/inferno_devilish_plan.tex
- campaigns/inferno_steadwicks_fall.tex
- sections/credits.tex
- templates/campaign.tex
- templates/cooperative.tex
- translations/credits.tex/credits.tex.pot
- translations/credits.tex/cs.po
- translations/credits.tex/fr.po
- translations/credits.tex/pl.po
- translations/inferno_deal_with_the_devil.tex/cs.po
- translations/inferno_deal_with_the_devil.tex/fr.po
- translations/inferno_deal_with_the_devil.tex/inferno_deal_with_the_devil.tex.pot
- translations/inferno_deal_with_the_devil.tex/pl.po
- translations/inferno_devilish_plan.tex/cs.po
- translations/inferno_devilish_plan.tex/fr.po
- translations/inferno_devilish_plan.tex/inferno_devilish_plan.tex.pot
- translations/inferno_devilish_plan.tex/pl.po
- translations/inferno_steadwicks_fall.tex/cs.po
- translations/inferno_steadwicks_fall.tex/fr.po
- translations/inferno_steadwicks_fall.tex/inferno_steadwicks_fall.tex.pot
- translations/inferno_steadwicks_fall.tex/pl.po
> the rest, and templates

- docs/scenarios.md
The map generator tool was updated faster than I thought so my recent changes are already useless and that's good :D
> Delete obsolete docs

- .github/CODEOWNERS
- .github/workflows/build-and-publish.yaml
- README.md
- main_cs.tex
- metadata.tex
- translations/bloody_grail.tex/cs.po
- translations/emerald_island.tex/cs.po
- translations/inferno_deal_with_the_devil.tex/cs.po
- translations/inferno_devilish_plan.tex/cs.po
- translations/inferno_steadwicks_fall.tex/cs.po
- translations/sentinels.tex/cs.po
- translations/the_hunt.tex/cs.po
- translations/titans_stronghold.tex/cs.po
> [CS] Bloody Grail

- README.md
- translations/emerald_island.tex/cs.po
- translations/inferno_deal_with_the_devil.tex/cs.po
- translations/inferno_devilish_plan.tex/cs.po
- translations/inferno_steadwicks_fall.tex/cs.po
- translations/sentinels.tex/cs.po
- translations/the_hunt.tex/cs.po
- translations/titans_stronghold.tex/cs.po
> [CS] Sentinels

- .github/workflows/check-tabs.yaml
- README.md
- campaigns/inferno_deal_with_the_devil.tex
- campaigns/inferno_devilish_plan.tex
- campaigns/inferno_steadwicks_fall.tex
- translations/inferno_deal_with_the_devil.tex/cs.po
- translations/inferno_deal_with_the_devil.tex/fr.po
- translations/inferno_deal_with_the_devil.tex/inferno_deal_with_the_devil.tex.pot
- translations/inferno_deal_with_the_devil.tex/pl.po
- translations/inferno_devilish_plan.tex/cs.po
- translations/inferno_devilish_plan.tex/fr.po
- translations/inferno_devilish_plan.tex/inferno_devilish_plan.tex.pot
- translations/inferno_devilish_plan.tex/pl.po
- translations/inferno_steadwicks_fall.tex/cs.po
- translations/inferno_steadwicks_fall.tex/fr.po
- translations/inferno_steadwicks_fall.tex/inferno_steadwicks_fall.tex.pot
- translations/inferno_steadwicks_fall.tex/pl.po
> [PL] Steadwick's Fall + small formatting fixes

- README.md
- translations/emerald_island.tex/cs.po
- translations/inferno_deal_with_the_devil.tex/cs.po
- translations/inferno_devilish_plan.tex/cs.po
- translations/inferno_steadwicks_fall.tex/cs.po
- translations/titans_stronghold.tex/cs.po
> [CS] Emerald Island

- README.md
- translations/titans_stronghold.tex/cs.po
> [CS] Titans Stronghold

- sections/credits.tex
- translations/credits.tex/credits.tex.pot
- translations/credits.tex/cs.po
- translations/credits.tex/fr.po
- translations/credits.tex/pl.po
> [CS] Credits

- metadata.tex
> TOC format

- translations/emerald_island.tex/cs.po
- translations/recommendations.tex/cs.po
> [CS] Recommendations

- translations/dragoncurse_castle.tex/cs.po
> [CS] Dragoncurse Castle

- campaigns/inferno_steadwicks_fall.tex
- translations/inferno_deal_with_the_devil.tex/cs.po
- translations/inferno_steadwicks_fall.tex/cs.po
- translations/inferno_steadwicks_fall.tex/fr.po
- translations/inferno_steadwicks_fall.tex/inferno_steadwicks_fall.tex.pot
- translations/inferno_steadwicks_fall.tex/pl.po
> [CS] Inferno Campaign - Steadwick's Fall

- sections/what_to_play.tex
- translations/what_to_play.tex/cs.po
> [CS] What to play

- translations/force_of_will.tex/cs.po
> [CS] Force of Will

- draft-scenarios/campaigns/castle_greek_gift.tex
- draft-scenarios/campaigns/castle_sicilian_dragon.tex
- draft-scenarios/campaigns/castle_two_knights_defense.tex
minor changes to rules and text per player feedback
> The Queen's Gambit 1.1

- .github/workflows/build-and-publish.yaml
- README.md
- main_fr.tex
Also add weblate status badges.
> Add French

- draft-scenarios/clash/arcane_artillery.tex
> Updated starting army arcane_artillery.tex

- .github/workflows/build-and-publish-draft.yaml
- .github/workflows/invalidate-cache.yaml
Introducing a bot to clear cache. Just type a comment:
Invalidate cache your-cache-key-
And the bot will take care of the rest.
> Introduce cache invalidation

- README.md
- translations/random_scenario.tex/pl.po
> [PL] Translate random scenario

- draft-scenarios/clash/shattered_alliance.tex
> Shattered Alliance - starting units
